# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Dojify
tagline:          Learn, Earn and Share
description:      "Get connected with the expert Options Traders. Log, Share and Analyze your trades, discuss with the fellow traders and take your options trading skill to the next level."
url:              https://dojify.com
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           spyonspy
  url:            https://twitter.com/dojify

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
